Repository DaviBahiense/Api-linkr, pull requests merged in 2022-03, with the labels that each got.

#5 feat:edit post
  src/controllers/authController.js
  src/controllers/postController.js
  src/repositories/postRepository.js
  src/routes/postRouter.js
  src/schemas/postSchema.js
Labels: enhancement

#6 Likes
  package-lock.json
  src/controllers/likeController.js
  src/middlewares/checkPostExistence.js
  src/repositories/likeRepository.js
  src/routes/index.js
  src/routes/likeRouter.js
Labels: enhancement

#8 Feat/delete
  src/controllers/postController.js
  src/repositories/postRepository.js
  src/routes/postRouter.js
Labels: enhancement

#9 feat: page users
  src/app.js
  src/controllers/userController.js
  src/repositories/userRepository.js
  src/routes/userRouter.js
Labels: enhancement

#11 Feat/hashtag controller
  package-lock.json
  package.json
  src/controllers/postController.js
  src/controllers/tagsController.js
  src/repositories/postRepository.js
  src/repositories/tagsRepository.js
  src/routes/index.js
  src/routes/tagsRouter.js
Labels: enhancement

#14 feat: follow
  database-linkr/scripts/004-cria-tag.sql
  database-linkr/scripts/005-cria-postTag.sql
  src/controllers/followController.js
  src/controllers/likeController.js
  src/middlewares/checkUserExistence.js
  src/repositories/followRepository.js
  src/repositories/tagsRepository.js
  src/routes/followRouter.js
  src/routes/index.js
Labels: enhancement

#16 Feat/comments
  src/controllers/commentController.js
  src/repositories/commentRepository.js
  src/repositories/userRepository.js
  src/routes/commentRouter.js
  src/routes/index.js
Labels: enhancement

#17 Feat/comments
  src/controllers/followController.js
  src/controllers/postController.js
  src/repositories/followRepository.js
  src/routes/followRouter.js
Labels: bug, enhancement

#18 fix
  src/repositories/tagsRepository.js
Labels: bug
